// 	Code generated by protoc-gen-go-http. DO NOT EDIT.
// 	Address https://github.com/elfpuck/grpc-http/protoc-gen-go-http
//
// 	version:
// 	protoc-gen-go-http 1.0.0
// 	protoc             v3.13.0
// 	created            2021-02-03 10:46:03
// 	source             pb/demo.proto

package demo

import (
	context "context"
	elfHttp "github.com/elfpuck/grpc-http/elfHttp"
	grpc "google.golang.org/grpc"
)

// 注册 Demo
func RegisterDemoFromEndpoint(ctx context.Context, service *elfHttp.Service, endpoint string, opts ...grpc.DialOption) error {
	conn, err := grpc.DialContext(ctx, endpoint, opts...)
	if err != nil {
		return err
	}
	return registerDemoHandlerClient(service, NewDemoClient(conn))
}

// 注册Method
func registerDemoHandlerClient(s *elfHttp.Service, client DemoClient) error {

	s.Method("Echo", func(c *elfHttp.Ctx) {
		params := new(Ping)
		if err := c.Unmarshal(params); err != nil {
			c.Result(nil, err)
			return
		}
		c.Result(client.Echo(c.Context, params, grpc.Header(&c.ResHeaderMD), grpc.Trailer(&c.ResTrailerMD)))
	})

	return nil
}
